// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: bot.proto

package bot

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SendCommandModel with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SendCommandModel) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendCommandModel with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendCommandModelMultiError, or nil if none found.
func (m *SendCommandModel) ValidateAll() error {
	return m.validate(true)
}

func (m *SendCommandModel) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BotId

	if _, ok := _SendCommandModel_Command_InLookup[m.GetCommand()]; !ok {
		err := SendCommandModelValidationError{
			field:  "Command",
			reason: "value must be in list [mode_out_of_service mode_operational stop_alarm power_off]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return SendCommandModelMultiError(errors)
	}
	return nil
}

// SendCommandModelMultiError is an error wrapping multiple validation errors
// returned by SendCommandModel.ValidateAll() if the designated constraints
// aren't met.
type SendCommandModelMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendCommandModelMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendCommandModelMultiError) AllErrors() []error { return m }

// SendCommandModelValidationError is the validation error returned by
// SendCommandModel.Validate if the designated constraints aren't met.
type SendCommandModelValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendCommandModelValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendCommandModelValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendCommandModelValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendCommandModelValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendCommandModelValidationError) ErrorName() string { return "SendCommandModelValidationError" }

// Error satisfies the builtin error interface
func (e SendCommandModelValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendCommandModel.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendCommandModelValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendCommandModelValidationError{}

var _SendCommandModel_Command_InLookup = map[string]struct{}{
	"mode_out_of_service": {},
	"mode_operational":    {},
	"stop_alarm":          {},
	"power_off":           {},
}
