// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: price.proto

package price

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on PriceModel with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PriceModel) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PriceModel with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PriceModelMultiError, or
// nil if none found.
func (m *PriceModel) ValidateAll() error {
	return m.validate(true)
}

func (m *PriceModel) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if _, ok := _PriceModel_Metal_InLookup[m.GetMetal()]; !ok {
		err := PriceModelValidationError{
			field:  "Metal",
			reason: "value must be in list [au ag]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return PriceModelMultiError(errors)
	}
	return nil
}

// PriceModelMultiError is an error wrapping multiple validation errors
// returned by PriceModel.ValidateAll() if the designated constraints aren't met.
type PriceModelMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PriceModelMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PriceModelMultiError) AllErrors() []error { return m }

// PriceModelValidationError is the validation error returned by
// PriceModel.Validate if the designated constraints aren't met.
type PriceModelValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PriceModelValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PriceModelValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PriceModelValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PriceModelValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PriceModelValidationError) ErrorName() string { return "PriceModelValidationError" }

// Error satisfies the builtin error interface
func (e PriceModelValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPriceModel.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PriceModelValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PriceModelValidationError{}

var _PriceModel_Metal_InLookup = map[string]struct{}{
	"au": {},
	"ag": {},
}

// Validate checks the field values on PriceResult with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PriceResult) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PriceResult with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PriceResultMultiError, or
// nil if none found.
func (m *PriceResult) ValidateAll() error {
	return m.validate(true)
}

func (m *PriceResult) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Price

	if len(errors) > 0 {
		return PriceResultMultiError(errors)
	}
	return nil
}

// PriceResultMultiError is an error wrapping multiple validation errors
// returned by PriceResult.ValidateAll() if the designated constraints aren't met.
type PriceResultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PriceResultMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PriceResultMultiError) AllErrors() []error { return m }

// PriceResultValidationError is the validation error returned by
// PriceResult.Validate if the designated constraints aren't met.
type PriceResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PriceResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PriceResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PriceResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PriceResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PriceResultValidationError) ErrorName() string { return "PriceResultValidationError" }

// Error satisfies the builtin error interface
func (e PriceResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPriceResult.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PriceResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PriceResultValidationError{}
