// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: storage.proto

package storage

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on StateModel with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *StateModel) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StateModel with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in StateModelMultiError, or
// nil if none found.
func (m *StateModel) ValidateAll() error {
	return m.validate(true)
}

func (m *StateModel) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BotId

	if len(errors) > 0 {
		return StateModelMultiError(errors)
	}
	return nil
}

// StateModelMultiError is an error wrapping multiple validation errors
// returned by StateModel.ValidateAll() if the designated constraints aren't met.
type StateModelMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StateModelMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StateModelMultiError) AllErrors() []error { return m }

// StateModelValidationError is the validation error returned by
// StateModel.Validate if the designated constraints aren't met.
type StateModelValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StateModelValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StateModelValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StateModelValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StateModelValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StateModelValidationError) ErrorName() string { return "StateModelValidationError" }

// Error satisfies the builtin error interface
func (e StateModelValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStateModel.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StateModelValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StateModelValidationError{}

// Validate checks the field values on OccupiedCell with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OccupiedCell) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OccupiedCell with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OccupiedCellMultiError, or
// nil if none found.
func (m *OccupiedCell) ValidateAll() error {
	return m.validate(true)
}

func (m *OccupiedCell) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Domain

	// no validation rules for Transaction

	if len(errors) > 0 {
		return OccupiedCellMultiError(errors)
	}
	return nil
}

// OccupiedCellMultiError is an error wrapping multiple validation errors
// returned by OccupiedCell.ValidateAll() if the designated constraints aren't met.
type OccupiedCellMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OccupiedCellMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OccupiedCellMultiError) AllErrors() []error { return m }

// OccupiedCellValidationError is the validation error returned by
// OccupiedCell.Validate if the designated constraints aren't met.
type OccupiedCellValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OccupiedCellValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OccupiedCellValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OccupiedCellValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OccupiedCellValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OccupiedCellValidationError) ErrorName() string { return "OccupiedCellValidationError" }

// Error satisfies the builtin error interface
func (e OccupiedCellValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOccupiedCell.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OccupiedCellValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OccupiedCellValidationError{}

// Validate checks the field values on StateResult with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *StateResult) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StateResult with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in StateResultMultiError, or
// nil if none found.
func (m *StateResult) ValidateAll() error {
	return m.validate(true)
}

func (m *StateResult) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	{
		sorted_keys := make([]string, len(m.GetOccupiedCells()))
		i := 0
		for key := range m.GetOccupiedCells() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetOccupiedCells()[key]
			_ = val

			// no validation rules for OccupiedCells[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, StateResultValidationError{
							field:  fmt.Sprintf("OccupiedCells[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, StateResultValidationError{
							field:  fmt.Sprintf("OccupiedCells[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return StateResultValidationError{
						field:  fmt.Sprintf("OccupiedCells[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	// no validation rules for Total

	// no validation rules for Available

	if len(errors) > 0 {
		return StateResultMultiError(errors)
	}
	return nil
}

// StateResultMultiError is an error wrapping multiple validation errors
// returned by StateResult.ValidateAll() if the designated constraints aren't met.
type StateResultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StateResultMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StateResultMultiError) AllErrors() []error { return m }

// StateResultValidationError is the validation error returned by
// StateResult.Validate if the designated constraints aren't met.
type StateResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StateResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StateResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StateResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StateResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StateResultValidationError) ErrorName() string { return "StateResultValidationError" }

// Error satisfies the builtin error interface
func (e StateResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStateResult.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StateResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StateResultValidationError{}
